version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # Native TCP
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=ch_pass
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server

volumes:
  ch_data:
  ch_logs:
